language: rust
env:
  - RUST_BACKTRACE=1

matrix:
  include:
    # Stable tests
    - rust: stable
      env:
        - RUST_BACKTRACE=1
      script:
        - cargo fmt --all -- --check
        - cargo test --all --features=checks

    # Nightly tests
    - rust: nightly
      env:
        - RUST_BACKTRACE=1
      script:
        - cargo test --all --features=checks
