[package]
name = "guillotiere"
version = "0.1.0"
authors = ["Nicolas Silva <nical@fastmail.com>"]
edition = "2018"
license = "MIT"
description = "A dynamic 2D texture atlas allocator with fast deallocation."

[features]
checks = []
serialization = ["serde", "euclid/serde"]

[dependencies]
euclid = "0.19.5"
serde = { version = "1.0", optional = true, features = ["serde_derive"] }